### ISSUE TITLE
Falat error with currupted code PHP 8.3

### ISSUE THREAD

**Issue by PavelFil** [duzun/hQuery.php#91]
Hello. This code catch a fatal error on PHP 8.3:
```php
hQuery::fromHTML('<iframe><meta http-equiv="refresh" content="1;/>');
```
Output:
```
PHP Fatal error:  Uncaught ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /vendor/duzun/hquery/src/hQuery/HTML_Index.php:410
Stack trace:
#0 /vendor/duzun/hquery/src/hQuery/HTML_Index.php(410): strpos()
#1 /vendor/duzun/hquery/src/hQuery/HTML_Index.php(230): duzun\hQuery\HTML_Index::detect_charset()
#2 /vendor/duzun/hquery/src/hQuery.php(84): duzun\hQuery\HTML_Index->__construct()
#3 /test.php(3): duzun\hQuery::fromHTML()
#4 {main}
  thrown in /vendor/duzun/hquery/src/hQuery/HTML_Index.php on line 410
```
I would prefer to receive exception.
Temporary solution is to add `</html>` at the end:
```php
hQuery::fromHTML('<iframe><meta http-equiv="refresh" content="1;/></html>');
```

**Comment by duzun** [comment]
Fixed in [#37b41605](https://github.com/duzun/hQuery.php/commit/37b416052d8a2275422443f5b2a580aa5f47c17e).

Thank you for catching this issue!
